<?php
/**
 * Medical Disclaimer.
 */
get_header(); ?>
<main>
<section class="legal-split legal-intro-only"><div><p class="eyebrow">Medical Disclaimer</p><h1>Read this before changing anything.</h1><p><strong>Last Updated:</strong> <?php echo esc_html(nirog_bhumi_policy_last_updated()); ?></p><p>Nirog Bhumi operates in the field of diabetes reversal through structured lifestyle transformation, integrating food regulation, yoga, naturopathy, Ayurveda-inspired practices, acupressure, meditation, breathwork, sleep and stress regulation, habit tracking and community support. If you take diabetes medication or insulin, continue it as advised by your doctor. Any changes should be made only after medical review by your doctor, especially if your blood sugar begins to improve.</p></div></section>
<section class="accordion-section">
  <details open><summary>3.1 Diabetes Reversal Programs Only</summary><p>Nirog Bhumi provides diabetes-focused wellness programs, wellness education, lifestyle guidance, natural health practices, yoga-based support, naturopathy-inspired routines, meditation, habit tracking, community support and curated wellness products that are geared toward diabetes reversal. Nirog Bhumi does not provide medical diagnosis, emergency care, prescription, surgery, hospital treatment or replacement for a qualified medical practitioner.</p></details>
  <details><summary>3.2 Not a Substitute for Medical Advice</summary><p>The content, consultations, programs, product information, yoga practices, naturopathy routines, diet guidance, habit tracking and educational materials provided by Nirog Bhumi are for general wellness and lifestyle support, and our programs are designed to assist in diabetes reversal. They should not be treated as medical advice, diagnosis or treatment. You should always consult your doctor, diabetologist or qualified healthcare professional regarding your medical condition, medicines, insulin, lab reports, symptoms, complications and treatment decisions.</p></details>
  <details><summary>3.3 Medication and Insulin Safety</summary><p>Do not stop, reduce, increase or change diabetes medicines, insulin, blood pressure medicines, cholesterol medicines or any other prescribed medication without consulting your treating doctor. Lifestyle changes, diet changes, fasting, weight loss, yoga, increased activity, herbs, supplements or natural products may affect blood sugar and medication needs. Any medication adjustment must be made only under medical supervision.</p></details>
  <details><summary>3.4 Emergency Situations</summary><p>Nirog Bhumi does not provide emergency care. If you experience very high blood sugar, very low blood sugar, fainting, confusion, chest pain, breathlessness, severe weakness, severe dehydration, infection, vomiting, unconsciousness, stroke-like symptoms, severe abdominal pain or any urgent medical condition, immediately contact your doctor, nearest hospital or emergency medical services.</p></details>
  <details><summary>3.5 Individual Suitability</summary><p>Not all practices, programs, foods, herbs, products, exercises or routines are suitable for everyone. People with heart disease, kidney disease, liver disease, pregnancy, recent surgery, severe weakness, eye disease, uncontrolled blood pressure, neuropathy, foot ulcers, advanced diabetes complications, eating disorders, elderly frailty or any serious condition are advised to consult their doctor or a qualified healthcare professional before starting our program or using any related products.</p></details>
  <details><summary>3.6 No Guaranteed Outcome</summary><p>Nirog Bhumi does not guarantee diabetes reversal, remission, cure, reduction of medication, weight loss, HbA1c reduction, improvement in blood sugar, improvement in symptoms or any specific result. Outcomes vary from person to person.</p></details>
  <details><summary>3.7 Product Disclaimer</summary><p>Products sold or facilitated through the Platform, including herbs, foods, wellness tools, yoga products, acupressure products or kits, are not intended to diagnose, treat, cure or prevent any disease unless specifically permitted under applicable law. Read labels, ingredients, instructions, warnings and expiry dates before use. If you have allergies, medical conditions, pregnancy, are taking medications or have any doubt, consult your doctor before using any product.</p></details>
  <details><summary>3.8 Reliance on Information</summary><p>Your use of any information, program, practice, product or service offered by Nirog Bhumi is at your own discretion and risk. You are responsible for seeking appropriate medical advice before acting on any health-related information.</p></details>
</section>
<?php nirog_bhumi_policy_contact_block(); ?>
</main>
<?php get_footer(); ?>
