<?php
/**
 * Static Nirog Bhumi template generated from programmes/yoga-interest-form.html.
 */
get_header(); ?>
<main>
<section class="interest-page yoga-interest-form-only">
  <div class="yoga-interest-heading"><p class="eyebrow">Register interest</p><h1>Yoga for Diabetes Reversal</h1></div>
  <form class="interest-form-card" method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="nirog_form_entry_submit"><input type="hidden" name="form_type" value="Yoga for Diabetes Interest"><?php wp_nonce_field('nirog_form_entry_submit', 'nirog_form_entry_nonce'); ?>
    <div class="form-cluster"><span>01</span><h2>Contact</h2><label>Full name<input required name="name" autocomplete="name"></label><label>Email<input required type="email" name="email" autocomplete="email"></label><div class="international-phone"><label>Country code<input required name="country_code" value="+91" inputmode="tel" autocomplete="tel-country-code" pattern="\+[0-9]{1,4}" aria-label="Country calling code"></label><label>Phone / WhatsApp<input required name="phone" inputmode="tel" autocomplete="tel-national" pattern="[0-9 ()-]{6,20}"></label></div></div>
    <div class="form-cluster"><span>02</span><h2>Health context</h2><label>Diabetes context<select name="diabetes_context"><option>Type 2 diabetes</option><option>Prediabetes</option><option>Insulin resistance</option><option>General metabolic health</option><option>Prefer not to say</option></select></label><label>Health conditions, pain or limitations<textarea rows="4" name="limitations" placeholder="Share back, knee, blood pressure, heart, vertigo, surgery or other concerns relevant to safe practice."></textarea></label></div>
    <div class="form-cluster wide"><span>03</span><h2>Your goals</h2><label>What would you like the practice to support?<textarea rows="5" name="message" placeholder="Diabetes reversal, glucose regulation, mobility, strength, stress, sleep, digestion, discipline or another goal."></textarea></label><label>Preferred practice time<select name="practice_time"><option>Morning</option><option>Evening</option><option>Flexible</option></select></label></div>
    <div class="form-cluster wide consent-copy"><span>04</span><h2>Data consent</h2><p><strong>Data consent:</strong> I consent to Nirog Bhumi collecting and processing my personal and health-related information, including my name, contact details, diabetes history, lifestyle information, medication context, and any reports or information shared by me, for the purpose of the Yoga for Diabetes Reversal program.</p><p>I understand that my information will be handled as per Nirog Bhumi's Privacy Policy, that I may request access, correction, or withdrawal of consent by emailing <a href="mailto:priyanshu@nirogbhumi.com">priyanshu@nirogbhumi.com</a>, and that withdrawal of consent may affect Nirog Bhumi's ability to provide follow-up services.</p></div>
    <label class="check"><input required type="checkbox" name="safety_consent"> I will share relevant health limitations and practise under appropriate guidance.</label><label class="check"><input required type="checkbox" name="data_processing_consent"> I consent to the collection and processing of my data as described above.</label><button class="pill primary" type="submit">Register Interest</button><p data-form-status></p>
  </form>
</section>
</main>
<?php get_footer(); ?>