<?php
/**
 * Static Nirog Bhumi template generated from pages/consultation-intake.html.
 */
get_header(); ?>
<main>
<section class="page-hero slim"><p class="eyebrow">Step 01 / intake</p><h1>Tell us your sugar story before booking.</h1><p>Share your reports, medicines, food timing, sleep and stress pattern so the consultation can begin with clarity instead of guesswork.</p></section>
<section class="form-section intake-form"><form data-demo-form data-redirect="consultation-payment.html"><label>Full name<input required name="name" autocomplete="name"></label><label>Email<input required type="email" name="email" autocomplete="email"></label><label>Phone / WhatsApp<input required name="phone" autocomplete="tel"></label><label>Primary concern<select required name="concern"><option>Type 2 diabetes</option><option>Pre-diabetes</option><option>Insulin resistance</option><option>Weight and sugar control</option><option>Yoga consultation</option></select></label><label>Latest HbA1c / fasting sugar if known<input name="reports" placeholder="Example: HbA1c 8.2, fasting 145"></label><label>Current medicines or insulin<textarea rows="4" name="medicines" placeholder="Medicine names, insulin, dose if comfortable sharing"></textarea></label><label>Typical day and meal timing<textarea rows="4" name="food" placeholder="Wake time, breakfast, lunch, dinner, snacks, tea, late-night eating"></textarea></label><label>Sleep, stress and activity<textarea rows="4" name="lifestyle" placeholder="Sleep time, stress level, walking, yoga, work hours"></textarea></label><label>Main goal for consultation<textarea rows="5" name="goal"></textarea></label><label class="check"><input required type="checkbox" name="consent"> I understand this is not emergency care and medical changes must be discussed with my doctor.</label><button class="pill primary" type="submit">Continue to Booking Amount</button><p data-form-status></p></form><aside><h2>Keep ready</h2><p>Recent HbA1c, fasting and post-meal sugar, lipid profile, medicine names, insulin details if any, and a simple note of your usual food and sleep routine.</p></aside></section>
</main>
<?php get_footer(); ?>