<?php
/**
 * Privacy Policy.
 */
get_header(); ?>
<main>
<section class="legal-split legal-intro-only"><div><p class="eyebrow">Privacy Policy</p><h1>Your health details deserve care.</h1><p><strong>Last Updated:</strong> <?php echo esc_html(nirog_bhumi_policy_last_updated()); ?></p><p>This Privacy Policy explains how Nirog Bhumi Private Limited ("Nirog Bhumi", "we", "us", "our") collects, uses, stores, shares, protects and otherwise processes your personal data when you access or use our Platform, book a consultation, purchase a product, join a program, interact with us, submit forms, communicate with us or use our services. By using the Platform or providing your information, you consent to the collection and use of your information in accordance with this Privacy Policy. If you do not agree with this Privacy Policy, please do not use the Platform or submit your personal data.</p></div></section>
<section class="accordion-section">
  <details open><summary>2.1 Information We Collect — Personal Information</summary><p>We may collect: name; age or date of birth; gender; phone number; email address; address; city, state and country; and identity or address information where required for legal, payment, delivery or compliance purposes.</p></details>
  <details><summary>2.2 Health and Lifestyle Information</summary><p>For consultations, programs, assessments or wellness guidance, we may collect: diabetes history; blood sugar readings; HbA1c reports; medication or insulin details; weight, waist, blood pressure and other health markers; food habits; sleep patterns; stress levels; physical activity; medical history; reports, prescriptions or test results voluntarily shared by you; and program adherence, habit tracking and progress information.</p></details>
  <details><summary>2.3 Transaction, Payment, Technical and Communication Information</summary><p>We may collect order and invoice details, payment status, delivery address, shipping and tracking details, refund/return/cancellation information and seller/partner-related order details. Payments are processed through third-party payment gateways; we do not store full card numbers, CVV, UPI PIN, banking passwords or OTPs. We may also collect technical and usage information (IP address, browser type, device information, operating system, cookies and session data, pages visited, time spent, interactions, analytics) and communication information (WhatsApp messages, phone calls, emails, chat support, consultation notes, feedback forms, community interactions and customer support conversations).</p></details>
  <details><summary>2.4 How We Use Your Information</summary><p>We may use your information to: provide consultations, programs, yoga sessions, products and services; understand your lifestyle, health context and goals; personalize program guidance and support; process orders, payments, invoices, refunds, returns and deliveries; coordinate with selected third-party sellers for order fulfilment; send consultation reminders, program updates, order updates and support messages; respond to queries, complaints and grievances; improve the Platform, services, content and user experience; conduct internal research, analytics and service improvement in aggregated or anonymized form; prevent fraud, misuse, illegal activity or security issues; comply with applicable laws, tax requirements, legal processes and regulatory obligations; and send educational or promotional communications, where permitted by law and subject to opt-out rights.</p></details>
  <details><summary>2.5 Health Data</summary><p>Health-related information is collected only where relevant for consultations, programs, wellness guidance, habit tracking, safety screening or service delivery. We use health information to understand your condition and support your journey toward diabetes reversal. We do not use health information to provide emergency care, diagnosis, prescription or replacement for medical treatment. You should not submit health information unless you are comfortable with us processing it for the purposes described in this Privacy Policy.</p></details>
  <details><summary>2.6 Sharing of Information</summary><p>We may share your information with: Nirog Bhumi team members, consultants, coaches or authorized personnel who need access for service delivery; payment gateways and payment service providers; technology, hosting, analytics, CRM, communication and cloud service providers; logistics partners, courier companies and delivery service providers; selected third-party sellers or partners, where necessary to fulfil your order; professional advisors, auditors, legal advisors or compliance consultants; government authorities, regulators, law enforcement agencies or courts where required by law; and successor entities in case of merger, restructuring, acquisition or transfer of business. Where information is shared with third-party sellers, it will generally be limited to what is necessary to process, pack, dispatch, deliver, service, replace, refund or resolve issues related to your order. We do not sell your personal health information to advertisers.</p></details>
  <details><summary>2.7 Third-Party Sellers</summary><p>If you purchase a product sold by a third-party seller through the Platform, your name, contact details, delivery address, order details and complaint/return details may be shared with the concerned seller for order fulfilment, customer support, return, replacement, refund or warranty purposes. Third-party sellers are expected to use your information only for fulfilling your order and related support; where a seller directly collects information from you outside the Platform, their own privacy policy may apply. Nirog Bhumi may require third-party sellers to follow appropriate confidentiality and data-protection practices, but shall not be responsible for any unauthorized use, misuse or breach of personal data caused by a seller's independent acts, omissions or systems, subject to applicable law.</p></details>
  <details><summary>2.8 Marketing Communications</summary><p>We may contact you by phone, SMS, WhatsApp, email, app notification or other means for service updates, educational content, offers, program information, product updates and follow-up. You may opt out of promotional communications by writing to us at <a href="mailto:priyanshu@nirogbhumi.com">priyanshu@nirogbhumi.com</a>. However, transactional and service-related communications may continue where necessary.</p></details>
  <details><summary>2.9 Cookies and Analytics</summary><p>We may use cookies and similar technologies to maintain sessions, improve user experience, understand traffic, remember preferences and analyze Platform usage. You may disable cookies in your browser settings, but some features of the Platform may not work properly.</p></details>
  <details><summary>2.10 Data Security</summary><p>We adopt reasonable security practices and procedures to protect your personal data from unauthorized access, loss, misuse, disclosure, alteration or destruction. However, no method of transmission over the internet or electronic storage is completely secure. By using the Platform, you acknowledge the inherent risks of internet-based data transmission. You are responsible for keeping your account credentials, communication links and access details confidential.</p></details>
  <details><summary>2.11 Data Retention</summary><p>We retain personal data only for as long as necessary for the purposes for which it was collected, including service delivery, program support, legal compliance, tax records, dispute resolution, fraud prevention, accounting, audit and legitimate business purposes. Health and consultation records may be retained for continuity of service, legal protection, safety, audit and compliance purposes unless deletion is requested and permitted under applicable law. We may retain anonymized or aggregated data for research, analytics, service improvement and development of wellness programs.</p></details>
  <details><summary>2.12 Research and Anonymized Use of Data</summary><p>Nirog Bhumi may use anonymized, aggregated or de-identified information for internal research, health insights, program improvement, educational content, impact assessment, product development and wellness research. Where possible, such information will not identify you personally. If any identifiable personal data is required for specific research, study, publication or external sharing, we will seek consent where required under applicable law.</p></details>
  <details><summary>2.13 Your Rights</summary><p>Subject to applicable law, you may request to access your personal data; correct inaccurate data; complete incomplete data; update outdated data; request erasure or deletion of personal data; withdraw consent for processing; and raise a grievance regarding processing of your personal data. Requests may be sent to <a href="mailto:priyanshu@nirogbhumi.com">priyanshu@nirogbhumi.com</a> with the subject line "Personal Data Request". We may verify your identity before acting on any request. Certain data may be retained where required by law, contract, tax, accounting, fraud prevention, dispute resolution or legitimate business purposes.</p></details>
  <details><summary>2.14 Withdrawal of Consent</summary><p>You may withdraw consent by writing to us at <a href="mailto:priyanshu@nirogbhumi.com">priyanshu@nirogbhumi.com</a>. Withdrawal of consent will not affect processing already carried out before the withdrawal. If the withdrawn information is necessary to provide a service, program, consultation, order or support, we may be unable to continue providing that service.</p></details>
  <details><summary>2.15 Data of Other Persons</summary><p>If you provide information about another person, including a family member, dependent or patient, you confirm that you have the authority and consent to provide such information to us.</p></details>
  <details><summary>2.16 Children</summary><p>The Platform is not intended for unsupervised use by minors. If a minor uses our Platform or services, it must be with the involvement and consent of a parent or lawful guardian.</p></details>
  <details><summary>2.17 Changes & Privacy Grievance Officer</summary><p>We may update this Privacy Policy from time to time. Any changes will be posted on the Platform, and significant changes may be communicated through appropriate channels where required. For privacy-related questions, correction, deletion, consent withdrawal or grievances, please contact our Grievance Officer Priyanshu Agarwal (Chief Operations Officer), Nirog Bhumi Private Limited, 18 Keshev Vihar, Gopalpura Bypass, Durgapura, Jaipur - 302018, Rajasthan, India. Email: <a href="mailto:priyanshu@nirogbhumi.com">priyanshu@nirogbhumi.com</a>. Phone: +91 9588810249. Working Hours: Monday to Friday, 9:00 AM to 6:00 PM, excluding public holidays.</p></details>
</section>
<?php nirog_bhumi_policy_contact_block(); ?>
</main>
<?php get_footer(); ?>
