<?php
/**
 * Shipping & Delivery Policy.
 */
get_header(); ?>
<main>
<section class="legal-split legal-intro-only"><div><p class="eyebrow">Shipping &amp; Delivery Policy</p><h1>How orders and services reach you.</h1><p><strong>Last Updated:</strong> <?php echo esc_html(nirog_bhumi_policy_last_updated()); ?></p><p>This Shipping &amp; Delivery Policy applies to physical products purchased through the Nirog Bhumi Platform, operated by Nirog Bhumi Private Limited. Consultations, programs, yoga sessions, subscriptions, digital content, habit tracking and other digital services are delivered online and do not require physical shipping.</p></div></section>
<section class="accordion-section">
  <details open><summary>6.1 Shipping Partners</summary><p>Orders may be shipped through registered courier companies, logistics partners, speed post, seller-managed delivery partners or other delivery providers. For third-party seller products, shipping may be handled by the seller, Nirog Bhumi, a logistics partner or a combination of these.</p></details>
  <details><summary>6.2 Dispatch Timeline</summary><p>Products will generally be dispatched within the timeline mentioned on the product page or order confirmation. Where no specific dispatch timeline is mentioned, we will endeavour to dispatch the order within 7 working days from the date of order confirmation and successful payment, subject to product availability, seller processing, holidays, logistics availability and other practical factors. Some products, kits, bundles, pre-orders, custom items or seller-fulfilled items may take longer.</p></details>
  <details><summary>6.3 Delivery Timeline</summary><p>Delivery timelines may vary depending on the delivery location, courier serviceability, seller location, product type, public holidays, weather, strikes, natural events, operational issues or other factors beyond our control. Estimated delivery timelines, if provided, are only estimates and not guaranteed delivery dates.</p></details>
  <details><summary>6.4 Delivery Address</summary><p>Orders will be delivered to the address provided by you at the time of purchase. You are responsible for providing a complete and accurate delivery address, phone number and other required details. Nirog Bhumi shall not be responsible for failed delivery, delay or loss due to incorrect address, incomplete address, wrong phone number, recipient unavailability or refusal to accept delivery.</p></details>
  <details><summary>6.5 Shipping Charges</summary><p>Shipping charges, if applicable, will be shown at the time of checkout or order confirmation. Shipping charges may be non-refundable unless the order is cancelled before dispatch or refund is approved due to a valid issue attributable to Nirog Bhumi or the seller.</p></details>
  <details><summary>6.6 Delivery Confirmation</summary><p>Delivery may be confirmed through courier tracking, delivery confirmation, OTP, signature, photo proof, status update, email, SMS, WhatsApp or other available method.</p></details>
  <details><summary>6.7 Delay in Delivery</summary><p>Nirog Bhumi shall not be liable for delivery delays caused by courier companies, postal authorities, third-party sellers, incorrect user details, force majeure events or circumstances beyond reasonable control. However, we will make reasonable efforts to assist you in tracking and resolving delivery issues.</p></details>
  <details><summary>6.8 Damaged Package at Delivery</summary><p>If the package appears visibly damaged, tampered with or opened at the time of delivery, you may refuse delivery and immediately inform us with photos/videos where possible. If you accept delivery and later find damage, defect, wrong product or missing items, you must report the issue within 48 hours of delivery as per our Return Policy.</p></details>
  <details><summary>6.9 Service Delivery</summary><p>For consultations, online programs, yoga sessions, subscriptions and digital services, delivery will be through online access, email, WhatsApp, video call link, app access, community access, program dashboard or other digital method communicated to you. Nirog Bhumi is not responsible for failure to access digital services due to user-side internet issues, device issues, incorrect contact details, missed communication or failure to check email/WhatsApp/app notifications.</p></details>
</section>
<?php nirog_bhumi_policy_contact_block(); ?>
</main>
<?php get_footer(); ?>
