<?php
/**
 * Cancellation & Refund Policy.
 */
get_header(); ?>
<main>
<section class="legal-split legal-intro-only"><div><p class="eyebrow">Cancellation &amp; Refund Policy</p><h1>Cancellations and refunds, explained clearly.</h1><p><strong>Last Updated:</strong> <?php echo esc_html(nirog_bhumi_policy_last_updated()); ?></p><p>This Cancellation &amp; Refund Policy applies to purchases, bookings, subscriptions, programs, services and products made through the Nirog Bhumi Platform, operated by Nirog Bhumi Private Limited. Refund eligibility may vary depending on whether the purchase relates to a consultation, digital service, program, subscription, product, kit or third-party seller product.</p></div></section>
<section class="accordion-section">
  <details open><summary>4.1 General Principles</summary><p>Refunds will be considered only in accordance with this policy. Approved refunds will be processed to the original payment method unless otherwise agreed. Payment gateway charges, convenience fees, taxes, shipping charges or administrative costs may be non-refundable where applicable. Refund timelines may depend on banks, payment gateways and payment service providers. Duplicate payments, failed transactions where money is debited, or excess payments will be verified and refunded where applicable. Nirog Bhumi reserves the right to refuse refund requests that are fraudulent, abusive, repeated, unreasonable or contrary to this policy.</p></details>
  <details><summary>4.2 Consultation Cancellation and Refund</summary><p>For online consultations: you may request cancellation or rescheduling at least 24 hours before the scheduled consultation time. If cancellation is requested at least 24 hours before, you may be eligible for a refund or rescheduling. If rescheduling is requested at least 24 hours before, we will make reasonable efforts to provide another available slot. If you do not attend the consultation or cancel less than 24 hours before the scheduled time, the consultation fee may be non-refundable. Once the consultation has been completed, no refund will be provided. If Nirog Bhumi cancels or is unable to conduct the consultation, you will be offered a rescheduled slot or refund.</p></details>
  <details><summary>4.3 Yoga Program / Subscription Cancellation and Refund</summary><p>For yoga programs, group sessions, subscriptions or digital access: if cancellation is requested before access to the program, session, recording, community, material or digital content has started, a refund may be considered. Once access to live sessions, recordings, program material, community group or digital content has been provided, the fee will generally be non-refundable. No refund will be provided for missed sessions, non-attendance or inability to follow the program after access has started. If Nirog Bhumi cancels a program before it begins, you may receive a refund or alternate program access. Subscription cancellation will stop future renewals where applicable, but does not automatically create a refund for the current billing period unless specifically approved.</p></details>
  <details><summary>4.4 Six-Month Program Cancellation and Refund</summary><p>For structured long-term programs, including the 6-Month Diabetes Reversal Program: cancellation requests made before onboarding, assessment, program access, group allocation, material sharing or consultation work has started may be eligible for refund. Once onboarding, assessment, group allocation, consultation, program access, coach support, habit tracking or material sharing has started, the fee may become partially or fully non-refundable. If cancellation is requested after program commencement, Nirog Bhumi may evaluate the request on a case-by-case basis. No refund will be provided merely because expected health results, diabetes reversal, remission, medication reduction, weight loss or HbA1c improvement were not achieved. No refund will be provided for non-participation, missed sessions, lack of adherence or voluntary withdrawal after access has started, unless otherwise approved by Nirog Bhumi. If Nirog Bhumi is unable to deliver a paid program, an appropriate refund, credit or alternate arrangement may be offered.</p></details>
  <details><summary>4.5 Product Order Cancellation</summary><p>For physical products, kits or items: cancellation requests may be accepted before the order is packed, dispatched or communicated to the seller/logistics partner for processing. Once the order has been packed, shipped or handed over for delivery, cancellation may not be possible. If cancellation is accepted before dispatch, the eligible refund will be processed as per this policy. If the product is sold by a third-party seller, cancellation approval may depend on the seller's processing stage and applicable product policy. For perishable, consumable, customized, hygiene-sensitive or opened products, cancellation after processing may not be allowed.</p></details>
  <details><summary>4.6 Third-Party Seller Products</summary><p>Where a product is sold by a third-party seller through the Platform: refunds and cancellations may be subject to seller-specific terms shown on the product page. Nirog Bhumi may assist in coordinating the refund or cancellation request. The seller may be required to verify product status, dispatch status, defect claims or return eligibility. Approved refunds will be processed through the Platform or payment channel, as applicable. Nirog Bhumi reserves the right to decide customer-facing resolution in coordination with the seller where required.</p></details>
  <details><summary>4.7 Damaged, Defective, Wrong or Missing Products</summary><p>If you receive a damaged, defective, wrong or incomplete product: you must report the issue within 48 hours of delivery; you must share order details, photos/videos of the product, packaging, invoice and the issue; the product must not be used, altered or disposed of before the issue is reviewed; after verification, Nirog Bhumi or the concerned seller may offer replacement, return, refund, store credit or other suitable resolution; if the claim is found to be false, incomplete or unsupported, the request may be rejected.</p></details>
  <details><summary>4.8 Refund Timeline</summary><p>Once a refund is approved, it will generally be processed within 7 to 14 working days. The actual time taken for the amount to reflect in your account may depend on your bank, card issuer, UPI provider or payment gateway.</p></details>
  <details><summary>4.9 Non-Refundable Cases</summary><p>Refunds may not be available for: completed consultations; missed consultations without timely cancellation; program access already provided; digital content, recordings or materials already shared; opened, used, damaged or tampered products; perishable, consumable or hygiene-sensitive products (unless defective or wrong item is delivered); health outcome not achieved; user changed mind after service delivery or product dispatch; incorrect information or wrong address provided by user; refusal to accept delivery without valid reason; delay caused by courier, address issue, force majeure or user unavailability; and any case specifically marked as non-refundable at the time of purchase.</p></details>
  <details><summary>4.10 How to Request Cancellation or Refund</summary><p>To request cancellation or refund, contact us at Email: <a href="mailto:priyanshu@nirogbhumi.com">priyanshu@nirogbhumi.com</a>, Phone: +91 9588810249, with the subject line "Cancellation / Refund Request". Required details: name, order ID, payment reference, product/service purchased, reason for request, and supporting photos/videos if applicable.</p></details>
</section>
<?php nirog_bhumi_policy_contact_block(); ?>
</main>
<?php get_footer(); ?>
