<?php
/**
 * Static Nirog Bhumi template generated from pages/policies.html.
 */
get_header(); ?>
<main>
  <section class="legal-split legal-intro-only">
    <div>
      <p class="eyebrow">Nirog Bhumi Policies</p>
      <h1>Clear rules for safe, respectful and lawful participation.</h1>
      <p>These Policies apply to the Nirog Bhumi website, consultations, diabetes reversal programs, yoga programs, wellness education, digital content, community groups, product purchases, payment facilities and all related services.</p>
      <p><strong>Definitions:</strong> "Nirog Bhumi", "we", "us" and "our" refer to Nirog Bhumi and authorised team members. "You", "user", "participant", "client" and "customer" refer to anyone using Nirog Bhumi services.</p>
      <p>If Nirog Bhumi operates through a registered legal entity, replace "Nirog Bhumi" with the full legal entity name before publishing.</p>
    </div>
  </section>

  <section class="accordion-section">
    <details open><summary>1. Website Terms and Conditions</summary><p>By accessing nirogbhumi.com, submitting forms, booking consultations, making payments, joining programs, downloading resources, joining groups, or communicating with us, you accept these Policies. Services are educational and lifestyle-oriented and do not replace emergency or specialist medical care. You must provide accurate information, participate safely, and use services lawfully. We may update website features, pricing, service structure, and these Policies at any time.</p></details>
    <details><summary>2. Medical Disclaimer</summary><p>Nirog Bhumi provides lifestyle education and support only. We do not provide diagnosis, emergency care, prescription, or medical treatment. Do not start, stop, or alter medicines or insulin without your treating doctor's supervision. No cure, remission, medicine reduction, or specific outcome is guaranteed. In emergencies such as severe low/high sugar, chest pain, breathlessness, fainting, stroke-like symptoms, severe infection, or self-harm thoughts, seek immediate emergency care.</p></details>
    <details><summary>3. Consultation Policy</summary><p>Consultations are for understanding health background and offering educational guidance. A booking is confirmed only after required details, payment (if applicable), and slot confirmation. Late attendance may shorten consultation time. No-show or late cancellation may be treated as consumed service. Rescheduling requests should be made at least 24 hours prior and are subject to availability. Consultation fees are generally non-refundable unless approved case-by-case. Recording without written permission is not allowed.</p></details>
    <details><summary>4. Program Terms and Participation Policy</summary><p>Programs may include food regulation, movement, yoga, pranayama, meditation, naturopathy, habit tracking, and check-ins. Results vary by individual and are not guaranteed. Participants must provide correct information, follow safety instructions, maintain respectful communication, and protect group privacy. We may modify program delivery for safety or operations. We may pause or remove participants for abusive behavior, unsafe advice, non-payment, policy violations, or confidentiality breaches.</p></details>
    <details><summary>5. Payments, Cancellation, Refund and Invoice Policy</summary><p>Prices and applicable taxes are shown before payment. Booking is confirmed only after successful payment. We use third-party payment providers and are not liable for their downtime or failures. You must provide accurate billing details. Consultation bookings are generally non-refundable after confirmation. Program refund eligibility depends on service stage and consumed value. Approved refunds may deduct gateway, administrative, tax, shipping, or used-service charges. Unresolved chargebacks may pause access.</p></details>
    <details><summary>6. Product Return, Replacement and Shipping Policy</summary><p>This applies to physical products including wellness kits, neti pots, tumblers, trackers, yoga/acupressure tools, and related items. Products are supportive wellness tools, not guaranteed cures. Shipping timelines are estimates. For damaged, defective, or incorrect products, contact us within 48 hours with order details and evidence. Opened/used hygiene-sensitive or consumable products may be non-returnable unless defective or incorrectly delivered. Approved returns must meet inspection conditions.</p></details>
    <details><summary>7. Online Payment Terms</summary><p>By using online payment links or facility, you accept payment terms. You are responsible for amount accuracy, billing details, authorization, and available balance. If payment fails, booking/order may remain unconfirmed. Verified duplicate or excess payments may be refunded to original mode where possible.</p></details>
    <details><summary>8. Privacy Policy and Data Consent</summary><p>We collect personal, billing, technical, communication, and health-related data required for service delivery, support, legal compliance, and operations. Sensitive health information is handled with additional care and is accessible only to authorized personnel and essential partners. We do not sell identifiable health data. You may request access, correction, and deletion where legally/operationally possible by contacting us at priyanshu@nirogbhumi.com. Data may be retained as required for legal, tax, safety, and operational purposes.</p></details>
    <details><summary>9. Cookie and Website Usage Policy</summary><p>We may use essential, analytics, preference, and marketing cookies or similar technologies. You can manage cookies via browser settings, but disabling them may impact website functionality.</p></details>
    <details><summary>10. Community and Communication Policy</summary><p>Community groups are for education and accountability, not emergency or prescription advice. Participants must be respectful and maintain confidentiality of other participants' personal and health details. Spam, harassment, abusive conduct, unsafe medication advice, and privacy breaches are prohibited. Violations may lead to removal without refund entitlement.</p></details>
    <details><summary>11. Intellectual Property Policy</summary><p>All website content, frameworks, routines, videos, articles, worksheets, brand assets, and learning materials are owned by or licensed to Nirog Bhumi unless stated otherwise. Materials are for personal use only. Reproduction, distribution, resale, commercial use, or brand misuse without written permission is prohibited.</p></details>
    <details><summary>12. Testimonials, Stories and Media Consent</summary><p>Identifiable testimonials, stories, photos, videos, and health progress data are used only with consent. Testimonials represent individual experiences and do not guarantee similar outcomes for others. Consent withdrawal requests will be honored for future use where reasonably possible.</p></details>
    <details><summary>13. Limitation of Liability</summary><p>To the maximum extent allowed by law, Nirog Bhumi is not liable for indirect or consequential loss arising from website/service use, health outcomes, unsupervised medicine changes, incorrect user-provided information, third-party service failures, downtime, or events beyond control. Where liability cannot be excluded, it is limited to the amount paid for the specific service/product in question, subject to law.</p></details>
    <details><summary>14. Indemnity</summary><p>You agree to indemnify Nirog Bhumi and related team members against claims/losses arising from policy breach, misleading information, unsafe usage, unlawful conduct, unauthorized sharing, privacy violations, or third-party rights violations caused by your actions.</p></details>
    <details><summary>15. Force Majeure</summary><p>Nirog Bhumi is not responsible for delays, interruptions, or non-performance caused by events beyond reasonable control including natural disaster, epidemic/pandemic, internet outages, government actions, strikes, illness, logistics disruption, payment downtime, or similar force majeure events. We may reschedule or provide alternate delivery where feasible.</p></details>
    <details><summary>16. Governing Law and Dispute Resolution</summary><p>These Policies are governed by Indian law. Disputes are subject to competent jurisdiction in Jaipur, Rajasthan, India, unless mandatory law requires otherwise. Parties should first attempt good-faith resolution before formal proceedings.</p></details>
    <details><summary>17. Contact and Grievance Redressal</summary><p>For policy queries, privacy requests, consent withdrawal, corrections, complaints, refund requests, and product concerns, contact: <a href="mailto:priyanshu@nirogbhumi.com">priyanshu@nirogbhumi.com</a>. Include your name, phone number, booking/order/program details and clear request. Responses are provided in a reasonable timeframe subject to verification and applicable law.</p></details>
  </section>
</main>
<?php get_footer(); ?>
