<?php
/**
 * Static Nirog Bhumi template generated from programmes/yoga-interest-form.html.
 */
get_header(); ?>
<main>
<section class="interest-page refined-interest yoga-interest-layout">
  <div class="interest-intro"><p class="eyebrow">Yoga for Diabetes</p><h1>Build a practice that fits your body.</h1><p>Share your experience, health context and preferred duration. We will review your details and recommend a safe, structured practice path.</p><div class="interest-points"><span>1, 3 or 6 months</span><span>Personalised progression</span><span>Diabetes-aware practice</span></div></div>
  <form class="interest-form-card" method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="nirog_form_entry_submit"><input type="hidden" name="form_type" value="Yoga for Diabetes Interest"><?php wp_nonce_field('nirog_form_entry_submit', 'nirog_form_entry_nonce'); ?>
    <div class="form-cluster"><span>01</span><h2>Contact</h2><label>Full name<input required name="name" autocomplete="name"></label><label>Email<input required type="email" name="email" autocomplete="email"></label><div class="international-phone"><label>Country code<input required name="country_code" value="+91" inputmode="tel" autocomplete="tel-country-code" pattern="\+[0-9]{1,4}" aria-label="Country calling code"></label><label>Phone / WhatsApp<input required name="phone" inputmode="tel" autocomplete="tel-national" pattern="[0-9 ()-]{6,20}"></label></div></div>
    <div class="form-cluster"><span>02</span><h2>Practice fit</h2><label>Preferred duration<select name="track"><option>1 month</option><option>3 months</option><option>6 months</option><option>Need a recommendation</option></select></label><label>Current yoga level<select name="level"><option>Complete beginner</option><option>Occasional practice</option><option>Regular beginner</option><option>Intermediate</option></select></label><label>Diabetes context<select name="diabetes_context"><option>Type 2 diabetes</option><option>Prediabetes</option><option>Insulin resistance</option><option>General metabolic health</option><option>Prefer not to say</option></select></label><label>Health conditions, pain or limitations<textarea rows="4" name="limitations" placeholder="Share back, knee, blood pressure, heart, vertigo, surgery or other concerns relevant to safe practice."></textarea></label></div>
    <div class="form-cluster wide"><span>03</span><h2>Your goals</h2><label>What would you like the practice to support?<textarea rows="5" name="message" placeholder="Glucose regulation, mobility, strength, stress, sleep, digestion, discipline or another goal."></textarea></label><label>Preferred practice time<select name="practice_time"><option>Morning</option><option>Evening</option><option>Flexible</option></select></label></div>
    <label class="check"><input required type="checkbox" name="safety_consent"> I will share relevant health limitations and practise under appropriate guidance.</label><button class="pill primary" type="submit">Register Interest</button><p data-form-status></p>
  </form>
  <aside class="interest-aside"><h2>What happens next?</h2><p>The team reviews your goals and limitations, then contacts you with the most suitable duration and next step.</p><ul><li>Your practice begins at your present capacity.</li><li>Health limitations are considered before progression.</li><li>Consistency is prioritised over intensity.</li></ul></aside>
</section>
</main>
<?php get_footer(); ?>