<?php
/**
 * Cancellation & Refund Policy.
 */
get_header(); ?>
<main>
<section class="legal-split legal-intro-only"><div><p class="eyebrow">Cancellation &amp; Refund Policy</p><h1>Cancellations and refunds, explained clearly.</h1><p><strong>Last Updated:</strong> <?php echo esc_html(nirog_bhumi_policy_last_updated()); ?></p></div></section>
<section class="accordion-section">
  <details open><summary>4.1 General Principles</summary><p>Refunds will be considered only in accordance with this policy. Approved refunds will be processed to the original payment method unless otherwise agreed. Payment gateway charges, convenience fees, taxes, shipping charges or administrative costs may be non-refundable where applicable. Refund timelines may depend on banks, payment gateways and payment service providers. Duplicate payments, failed transactions where money is debited, or excess payments will be verified and refunded where applicable. Nirog Bhumi reserves the right to refuse refund requests that are fraudulent, abusive, repeated, unreasonable or contrary to this policy.</p></details>
  <details><summary>4.2 Consultation Cancellation and Refund</summary><p>For online consultations: you may request cancellation or rescheduling at least 24 hours before the scheduled consultation time. If cancellation is requested at least 24 hours before, you may be eligible for a refund or rescheduling. If rescheduling is requested at least 24 hours before, we will make reasonable efforts to provide another available slot. If you do not attend the consultation or cancel less than 24 hours before the scheduled time, the consultation fee may be non-refundable. Once the consultation has been completed, no refund will be provided. If Nirog Bhumi cancels or is unable to conduct the consultation, you will be offered a rescheduled slot or refund.</p></details>
  <details><summary>4.3 Yoga Program / Subscription Cancellation and Refund</summary><p>For yoga programs, group sessions, subscriptions or digital access: if cancellation is requested before access to the program, session, recording, community, material or digital content has started, a refund may be considered. Once access to live sessions, recordings, program material, community group or digital content has been provided, the fee will generally be non-refundable. No refund will be provided for missed sessions, non-attendance or inability to follow the program after access has started. If Nirog Bhumi cancels a program before it begins, you may receive a refund or alternate program access. Subscription cancellation will stop future renewals where applicable, but does not automatically create a refund for the current billing period unless specifically approved.</p></details>
  <details><summary>4.4 Six-Month Program Cancellation and Refund</summary><p>For structured long-term programs, including the 6-Month Diabetes Reversal Program: cancellation requests made before onboarding, assessment, program access, group allocation, material sharing or consultation work has started may be eligible for refund. Once onboarding, assessment, group allocation, consultation, program access, coach support, habit tracking or material sharing has started, the fee may become partially or fully non-refundable. If cancellation is requested after program commencement, Nirog Bhumi may evaluate the request on a case-by-case basis. No refund will be provided merely because expected health results, diabetes reversal, remission, medication reduction, weight loss or HbA1c improvement were not achieved. No refund will be provided for non-participation, missed sessions, lack of adherence or voluntary withdrawal after access has started, unless otherwise approved by Nirog Bhumi. If Nirog Bhumi is unable to deliver a paid program, an appropriate refund, credit or alternate arrangement may be offered.</p></details>
  <details><summary>4.8 Refund Timeline</summary><p>Once a refund is approved, it will generally be processed within 7 to 14 working days. The actual time taken for the amount to reflect in your account may depend on your bank, card issuer, UPI provider or payment gateway.</p></details>
  <details><summary>4.10 How to Request Cancellation or Refund</summary><p>To request cancellation or refund, contact us at Email: <a href="mailto:priyanshu@nirogbhumi.com">priyanshu@nirogbhumi.com</a>, Phone: +91 9588810249, with the subject line "Cancellation / Refund Request". Required details: name, order ID, payment reference, product/service purchased, reason for request, and supporting photos/videos if applicable.</p></details>
</section>
<?php nirog_bhumi_policy_contact_block(); ?>
</main>
<?php get_footer(); ?>
